[General]
capture_frames = 10
n_camera = 1
smoothing_filter = 1
sensor_id = "Camera0"
set_roll = 0.0
set_pitch = 0.0
set_yaw = 0.0

[Selection]
pcl_cutoff_dist = 1.1
target_max_dist = 0.85
target_min_dist = 0.3
target_min_len = 0.25
target_max_len = 0.45
target_max_tilt = 30.0

[Camera0_Factory]
fx = 0
fy = 0
cx = 0
cy = 0
p1 = 0
p2 = 0
k1 = 0
k2 = 0
k3 = 0
k4 = 0
k5 = 0
k6 = 0

[Camera0]
camera_name = "camera0"
serial_no = "PD71A1EGD8280033P"
range1 = 0
range2 = 2
rgb_image = -1
height = 480
width = 640
fx = 0
fy = 0
cx = 0
cy = 0
rot_angle_roll = 0.0
rot_angle_pitch = 0.0
rot_angle_yaw = 0.0
translation_x = 0.0
translation_y = 0.0
translation_z = 0.0